/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 04/12/2009, 02:10:38 ص
 */
package tp3;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import tp3.GW1;
import tp3.GW2;
/**
 *
 * @author BRM
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("<html><h4> Choisir routeur:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Voisin", "Cout"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"N1", null, null},
                {"N2", null, null},
                {"N3", null, null},
                {"N4", null, null}
            },
            new String [] {
                "Node", "GW", "Cout"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "GW Source", "Voisin", "Cout"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel2.setText("<html><h3> Table d'Adjacence");

        jLabel3.setText("<html><h3> Table de Routage");

        jLabel4.setText("<html><h3>LSDB");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GW1", "GW2", "GW3", "GW4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setText("Dijkstra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextArea1InputMethodTextChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jTextArea1);

        jButton4.setText("Quitter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            // TODO add your handling code here:
            GW1 gw1 = new GW1();
            GW2 gw2 = new GW2();
            GW3 gw3 = new GW3();
            GW4 gw4 = new GW4();
            String choix = new String(jComboBox1.getSelectedItem().toString());
            System.out.println("choix : " + choix);
            if (choix.matches("GW1")) {
                //Table d'adjacence
                NewJFrame.jTable1.setValueAt(gw1.a1.Getvoisin(), 0, 0);
                NewJFrame.jTable1.setValueAt(gw1.a1.Getcout(), 0, 1);
                NewJFrame.jTable1.setValueAt(gw1.a2.Getvoisin(), 1, 0);
                NewJFrame.jTable1.setValueAt(gw1.a2.Getcout(), 1, 1);
                NewJFrame.jTable1.setValueAt(gw1.a3.Getvoisin(), 2, 0);
                NewJFrame.jTable1.setValueAt(gw1.a3.Getcout(), 2, 1);
                NewJFrame.jTable1.setValueAt(gw1.a4.Getvoisin(), 3, 0);
                NewJFrame.jTable1.setValueAt(gw1.a4.Getcout(), 3, 1);
                //LSDB
                NewJFrame.jTable3.setValueAt(gw1.l1.GetGW_source(), 0, 0);
                NewJFrame.jTable3.setValueAt(gw1.l1.Getvoisin(), 0, 1);
                NewJFrame.jTable3.setValueAt(gw1.l1.Getcout(), 0, 2);
                NewJFrame.jTable3.setValueAt(gw1.l2.GetGW_source(), 1, 0);
                NewJFrame.jTable3.setValueAt(gw1.l2.Getvoisin(), 1, 1);
                NewJFrame.jTable3.setValueAt(gw1.l2.Getcout(), 1, 2);
                NewJFrame.jTable3.setValueAt(gw1.l3.GetGW_source(), 2, 0);
                NewJFrame.jTable3.setValueAt(gw1.l3.Getvoisin(), 2, 1);
                NewJFrame.jTable3.setValueAt(gw1.l3.Getcout(), 2, 2);
                NewJFrame.jTable3.setValueAt(gw1.l4.GetGW_source(), 3, 0);
                NewJFrame.jTable3.setValueAt(gw1.l4.Getvoisin(), 3, 1);
                NewJFrame.jTable3.setValueAt(gw1.l4.Getcout(), 3, 2);
                NewJFrame.jTable3.setValueAt(gw1.l5.GetGW_source(), 4, 0);
                NewJFrame.jTable3.setValueAt(gw1.l5.Getvoisin(), 4, 1);
                NewJFrame.jTable3.setValueAt(gw1.l5.Getcout(), 4, 2);
                NewJFrame.jTable3.setValueAt(gw1.l6.GetGW_source(), 5, 0);
                NewJFrame.jTable3.setValueAt(gw1.l6.Getvoisin(), 5, 1);
                NewJFrame.jTable3.setValueAt(gw1.l6.Getcout(), 5, 2);
                NewJFrame.jTable3.setValueAt(gw1.l7.GetGW_source(), 6, 0);
                NewJFrame.jTable3.setValueAt(gw1.l7.Getvoisin(), 6, 1);
                NewJFrame.jTable3.setValueAt(gw1.l7.Getcout(), 6, 2);
                NewJFrame.jTable3.setValueAt(gw1.l8.GetGW_source(), 7, 0);
                NewJFrame.jTable3.setValueAt(gw1.l8.Getvoisin(), 7, 1);
                NewJFrame.jTable3.setValueAt(gw1.l8.Getcout(), 7, 2);
                NewJFrame.jTable3.setValueAt(gw1.l9.GetGW_source(), 8, 0);
                NewJFrame.jTable3.setValueAt(gw1.l9.Getvoisin(), 8, 1);
                NewJFrame.jTable3.setValueAt(gw1.l9.Getcout(), 8, 2);
                NewJFrame.jTable3.setValueAt(gw1.l10.GetGW_source(), 9, 0);
                NewJFrame.jTable3.setValueAt(gw1.l10.Getvoisin(), 9, 1);
                NewJFrame.jTable3.setValueAt(gw1.l10.Getcout(), 9, 2);
                NewJFrame.jTable3.setValueAt(gw1.l11.GetGW_source(), 10, 0);
                NewJFrame.jTable3.setValueAt(gw1.l11.Getvoisin(), 10, 1);
                NewJFrame.jTable3.setValueAt(gw1.l11.Getcout(), 10, 2);
                NewJFrame.jTable3.setValueAt(gw1.l12.GetGW_source(), 11, 0);
                NewJFrame.jTable3.setValueAt(gw1.l12.Getvoisin(), 11, 1);
                NewJFrame.jTable3.setValueAt(gw1.l12.Getcout(), 11, 2);
                NewJFrame.jTable3.setValueAt(gw1.l13.GetGW_source(), 12, 0);
                NewJFrame.jTable3.setValueAt(gw1.l13.Getvoisin(), 12, 1);
                NewJFrame.jTable3.setValueAt(gw1.l13.Getcout(), 12, 2);
                NewJFrame.jTable3.setValueAt(gw1.l14.GetGW_source(), 13, 0);
                NewJFrame.jTable3.setValueAt(gw1.l14.Getvoisin(), 13, 1);
                NewJFrame.jTable3.setValueAt(gw1.l14.Getcout(), 13, 2);
                
               
            }
            if (choix.matches("GW2")) {
                NewJFrame.jTable1.setValueAt(gw2.a1.Getvoisin(), 0, 0);
                NewJFrame.jTable1.setValueAt(gw2.a1.Getcout(), 0, 1);
                NewJFrame.jTable1.setValueAt(gw2.a2.Getvoisin(), 1, 0);
                NewJFrame.jTable1.setValueAt(gw2.a2.Getcout(), 1, 1);
                NewJFrame.jTable1.setValueAt(gw2.a3.Getvoisin(), 2, 0);
                NewJFrame.jTable1.setValueAt(gw2.a3.Getcout(), 2, 1);
                NewJFrame.jTable1.setValueAt("", 3, 0);
                NewJFrame.jTable1.setValueAt("", 3, 1);
                
                //LSDB
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(0).GetGW_source(), 0, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(0).Getvoisin(), 0, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(0).Getcout(), 0, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(1).GetGW_source(), 1, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(1).Getvoisin(), 1, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(1).Getcout(), 1, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(2).GetGW_source(), 2, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(2).Getvoisin(), 2, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(2).Getcout(), 2, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(3).GetGW_source(), 3, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(3).Getvoisin(), 3, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(3).Getcout(), 3, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(4).GetGW_source(), 4, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(4).Getvoisin(), 4, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(4).Getcout(), 4, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(5).GetGW_source(), 5, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(5).Getvoisin(), 5, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(5).Getcout(), 5, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(6).GetGW_source(), 6, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(6).Getvoisin(), 6, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(6).Getcout(), 6, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(7).GetGW_source(), 7, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(7).Getvoisin(), 7, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(7).Getcout(), 7, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(8).GetGW_source(), 8, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(8).Getvoisin(), 8, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(8).Getcout(), 8, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(9).GetGW_source(), 9, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(9).Getvoisin(), 9, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(9).Getcout(), 9, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(10).GetGW_source(), 10, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(10).Getvoisin(), 10, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(10).Getcout(), 10, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(11).GetGW_source(), 11, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(11).Getvoisin(), 11, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(11).Getcout(), 11, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(12).GetGW_source(), 12, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(12).Getvoisin(), 12, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(12).Getcout(), 12, 2);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(13).GetGW_source(), 13, 0);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(13).Getvoisin(), 13, 1);
                NewJFrame.jTable3.setValueAt(gw2.LSDB.get(13).Getcout(), 13, 2);
                
            }
            if (choix.matches("GW3")) {
                NewJFrame.jTable1.setValueAt(gw3.a1.Getvoisin(), 0, 0);
                NewJFrame.jTable1.setValueAt(gw3.a1.Getcout(), 0, 1);
                NewJFrame.jTable1.setValueAt(gw3.a2.Getvoisin(), 1, 0);
                NewJFrame.jTable1.setValueAt(gw3.a2.Getcout(), 1, 1);
                NewJFrame.jTable1.setValueAt(gw3.a3.Getvoisin(), 2, 0);
                NewJFrame.jTable1.setValueAt(gw3.a3.Getcout(), 2, 1);
                NewJFrame.jTable1.setValueAt(gw3.a4.Getvoisin(), 3, 0);
                NewJFrame.jTable1.setValueAt(gw3.a4.Getcout(), 3, 1);
                //LSDB
                NewJFrame.jTable3.setValueAt(gw3.l1.GetGW_source(), 0, 0);
                NewJFrame.jTable3.setValueAt(gw3.l1.Getvoisin(), 0, 1);
                NewJFrame.jTable3.setValueAt(gw3.l1.Getcout(), 0, 2);
                NewJFrame.jTable3.setValueAt(gw3.l2.GetGW_source(), 1, 0);
                NewJFrame.jTable3.setValueAt(gw3.l2.Getvoisin(), 1, 1);
                NewJFrame.jTable3.setValueAt(gw3.l2.Getcout(), 1, 2);
                NewJFrame.jTable3.setValueAt(gw3.l3.GetGW_source(), 2, 0);
                NewJFrame.jTable3.setValueAt(gw3.l3.Getvoisin(), 2, 1);
                NewJFrame.jTable3.setValueAt(gw3.l3.Getcout(), 2, 2);
                NewJFrame.jTable3.setValueAt(gw3.l4.GetGW_source(), 3, 0);
                NewJFrame.jTable3.setValueAt(gw3.l4.Getvoisin(), 3, 1);
                NewJFrame.jTable3.setValueAt(gw3.l4.Getcout(), 3, 2);
                NewJFrame.jTable3.setValueAt(gw3.l5.GetGW_source(), 4, 0);
                NewJFrame.jTable3.setValueAt(gw3.l5.Getvoisin(), 4, 1);
                NewJFrame.jTable3.setValueAt(gw3.l5.Getcout(), 4, 2);
                NewJFrame.jTable3.setValueAt(gw3.l6.GetGW_source(), 5, 0);
                NewJFrame.jTable3.setValueAt(gw3.l6.Getvoisin(), 5, 1);
                NewJFrame.jTable3.setValueAt(gw3.l6.Getcout(), 5, 2);
                NewJFrame.jTable3.setValueAt(gw3.l7.GetGW_source(), 6, 0);
                NewJFrame.jTable3.setValueAt(gw3.l7.Getvoisin(), 6, 1);
                NewJFrame.jTable3.setValueAt(gw3.l7.Getcout(), 6, 2);
                NewJFrame.jTable3.setValueAt(gw3.l8.GetGW_source(), 7, 0);
                NewJFrame.jTable3.setValueAt(gw3.l8.Getvoisin(), 7, 1);
                NewJFrame.jTable3.setValueAt(gw3.l8.Getcout(), 7, 2);
                NewJFrame.jTable3.setValueAt(gw3.l9.GetGW_source(), 8, 0);
                NewJFrame.jTable3.setValueAt(gw3.l9.Getvoisin(), 8, 1);
                NewJFrame.jTable3.setValueAt(gw3.l9.Getcout(), 8, 2);
                NewJFrame.jTable3.setValueAt(gw3.l10.GetGW_source(), 9, 0);
                NewJFrame.jTable3.setValueAt(gw3.l10.Getvoisin(), 9, 1);
                NewJFrame.jTable3.setValueAt(gw3.l10.Getcout(), 9, 2);
                NewJFrame.jTable3.setValueAt(gw3.l11.GetGW_source(), 10, 0);
                NewJFrame.jTable3.setValueAt(gw3.l11.Getvoisin(), 10, 1);
                NewJFrame.jTable3.setValueAt(gw3.l11.Getcout(), 10, 2);
                NewJFrame.jTable3.setValueAt(gw3.l12.GetGW_source(), 11, 0);
                NewJFrame.jTable3.setValueAt(gw3.l12.Getvoisin(), 11, 1);
                NewJFrame.jTable3.setValueAt(gw3.l12.Getcout(), 11, 2);
                NewJFrame.jTable3.setValueAt(gw3.l13.GetGW_source(), 12, 0);
                NewJFrame.jTable3.setValueAt(gw3.l13.Getvoisin(), 12, 1);
                NewJFrame.jTable3.setValueAt(gw3.l13.Getcout(), 12, 2);
                NewJFrame.jTable3.setValueAt(gw3.l14.GetGW_source(), 13, 0);
                NewJFrame.jTable3.setValueAt(gw3.l14.Getvoisin(), 13, 1);
                NewJFrame.jTable3.setValueAt(gw3.l14.Getcout(), 13, 2);
                
            }
            if (choix.matches("GW4")) {
                NewJFrame.jTable1.setValueAt(gw4.a1.Getvoisin(), 0, 0);
                NewJFrame.jTable1.setValueAt(gw4.a1.Getcout(), 0, 1);
                NewJFrame.jTable1.setValueAt(gw4.a2.Getvoisin(), 1, 0);
                NewJFrame.jTable1.setValueAt(gw4.a2.Getcout(), 1, 1);
                NewJFrame.jTable1.setValueAt(gw4.a3.Getvoisin(), 2, 0);
                NewJFrame.jTable1.setValueAt(gw4.a3.Getcout(), 2, 1);
                NewJFrame.jTable1.setValueAt("", 3, 0);
                NewJFrame.jTable1.setValueAt("", 3, 1);
                //LSDB
                NewJFrame.jTable3.setValueAt(gw4.l1.GetGW_source(), 0, 0);
                NewJFrame.jTable3.setValueAt(gw4.l1.Getvoisin(), 0, 1);
                NewJFrame.jTable3.setValueAt(gw4.l1.Getcout(), 0, 2);
                NewJFrame.jTable3.setValueAt(gw4.l2.GetGW_source(), 1, 0);
                NewJFrame.jTable3.setValueAt(gw4.l2.Getvoisin(), 1, 1);
                NewJFrame.jTable3.setValueAt(gw4.l2.Getcout(), 1, 2);
                NewJFrame.jTable3.setValueAt(gw4.l3.GetGW_source(), 2, 0);
                NewJFrame.jTable3.setValueAt(gw4.l3.Getvoisin(), 2, 1);
                NewJFrame.jTable3.setValueAt(gw4.l3.Getcout(), 2, 2);
                NewJFrame.jTable3.setValueAt(gw4.l4.GetGW_source(), 3, 0);
                NewJFrame.jTable3.setValueAt(gw4.l4.Getvoisin(), 3, 1);
                NewJFrame.jTable3.setValueAt(gw4.l4.Getcout(), 3, 2);
                NewJFrame.jTable3.setValueAt(gw4.l5.GetGW_source(), 4, 0);
                NewJFrame.jTable3.setValueAt(gw4.l5.Getvoisin(), 4, 1);
                NewJFrame.jTable3.setValueAt(gw4.l5.Getcout(), 4, 2);
                NewJFrame.jTable3.setValueAt(gw4.l6.GetGW_source(), 5, 0);
                NewJFrame.jTable3.setValueAt(gw4.l6.Getvoisin(), 5, 1);
                NewJFrame.jTable3.setValueAt(gw4.l6.Getcout(), 5, 2);
                NewJFrame.jTable3.setValueAt(gw4.l7.GetGW_source(), 6, 0);
                NewJFrame.jTable3.setValueAt(gw4.l7.Getvoisin(), 6, 1);
                NewJFrame.jTable3.setValueAt(gw4.l7.Getcout(), 6, 2);
                NewJFrame.jTable3.setValueAt(gw4.l8.GetGW_source(), 7, 0);
                NewJFrame.jTable3.setValueAt(gw4.l8.Getvoisin(), 7, 1);
                NewJFrame.jTable3.setValueAt(gw4.l8.Getcout(), 7, 2);
                NewJFrame.jTable3.setValueAt(gw4.l9.GetGW_source(), 8, 0);
                NewJFrame.jTable3.setValueAt(gw4.l9.Getvoisin(), 8, 1);
                NewJFrame.jTable3.setValueAt(gw4.l9.Getcout(), 8, 2);
                NewJFrame.jTable3.setValueAt(gw4.l10.GetGW_source(), 9, 0);
                NewJFrame.jTable3.setValueAt(gw4.l10.Getvoisin(), 9, 1);
                NewJFrame.jTable3.setValueAt(gw4.l10.Getcout(), 9, 2);
                NewJFrame.jTable3.setValueAt(gw4.l11.GetGW_source(), 10, 0);
                NewJFrame.jTable3.setValueAt(gw4.l11.Getvoisin(), 10, 1);
                NewJFrame.jTable3.setValueAt(gw4.l11.Getcout(), 10, 2);
                NewJFrame.jTable3.setValueAt(gw4.l12.GetGW_source(), 11, 0);
                NewJFrame.jTable3.setValueAt(gw4.l12.Getvoisin(), 11, 1);
                NewJFrame.jTable3.setValueAt(gw4.l12.Getcout(), 11, 2);
                NewJFrame.jTable3.setValueAt(gw4.l13.GetGW_source(), 12, 0);
                NewJFrame.jTable3.setValueAt(gw4.l13.Getvoisin(), 12, 1);
                NewJFrame.jTable3.setValueAt(gw4.l13.Getcout(), 12, 2);
                NewJFrame.jTable3.setValueAt(gw4.l14.GetGW_source(), 13, 0);
                NewJFrame.jTable3.setValueAt(gw4.l14.Getvoisin(), 13, 1);
                NewJFrame.jTable3.setValueAt(gw4.l14.Getcout(), 13, 2);
                
            }
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextArea1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextArea1InputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextArea1InputMethodTextChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
        String choix = new String(jComboBox1.getSelectedItem().toString());
        if (choix.matches("GW1")) {
 int i =0;
        Vertex v0 = new Vertex("GW1");
	Vertex v1 = new Vertex("GW2");
	Vertex v2 = new Vertex("GW3");
	Vertex v3 = new Vertex("GW4");

	v0.adjacencies = new Edge[]{ new Edge(v1,  7),
	                             new Edge(v2,  4),
                                     new Edge(v3,  1)};

	v1.adjacencies = new Edge[]{ new Edge(v0,  7),
	                             new Edge(v2,  10)};

	v2.adjacencies = new Edge[]{ new Edge(v0,  4),
                                     new Edge(v1,  10),
                                     new Edge(v3,  2)};

	v3.adjacencies = new Edge[]{ new Edge(v0, 1),
                                     new Edge(v2, 2)};


	Vertex[] vertices = { v0, v1, v2, v3 };

System.out.println("***********************************************");
        Dijkstra.computePaths(v0);
        for ( Vertex v : vertices)
	{
	    System.out.println("Distance to " + v + ": " + v.minDistance);
             NewJFrame.jTable2.setValueAt(v.minDistance, i, 2);
	    List<Vertex> path = Dijkstra.getShortestPathTo(v);
	    System.out.println("Path: " + path);
            NewJFrame.jTable2.setValueAt(path, i, 1);
                         i++;
       
      
       
System.out.println("Realiser par Bibomaster");
    }//GEN-LAST:event_jButton3ActionPerformed
 
    }
    if (choix.matches("GW2")) {
 int i =0;
        Vertex v0 = new Vertex("GW1");
	Vertex v1 = new Vertex("GW2");
	Vertex v2 = new Vertex("GW3");
	Vertex v3 = new Vertex("GW4");

	v0.adjacencies = new Edge[]{ new Edge(v1,  7),
	                             new Edge(v2,  4),
                                     new Edge(v3,  1)};

	v1.adjacencies = new Edge[]{ new Edge(v0,  7),
	                             new Edge(v2,  10)};

	v2.adjacencies = new Edge[]{ new Edge(v0,  4),
                                     new Edge(v1,  10),
                                     new Edge(v3,  2)};

	v3.adjacencies = new Edge[]{ new Edge(v0, 1),
                                     new Edge(v2, 2)};


	Vertex[] vertices = { v0, v1, v2, v3 };

System.out.println("***********************************************");
        Dijkstra.computePaths(v1);
        for ( Vertex v : vertices)
	{
	    System.out.println("Distance to " + v + ": " + v.minDistance);
             NewJFrame.jTable2.setValueAt(v.minDistance, i, 2);
	    List<Vertex> path = Dijkstra.getShortestPathTo(v);
	    System.out.println("Path: " + path);
            NewJFrame.jTable2.setValueAt(path, i, 1);
                         i++;



System.out.println("Realiser par Bibomaster");
    }

    }
    if (choix.matches("GW3")) {
 int i =0;
        Vertex v0 = new Vertex("GW1");
	Vertex v1 = new Vertex("GW2");
	Vertex v2 = new Vertex("GW3");
	Vertex v3 = new Vertex("GW4");

	v0.adjacencies = new Edge[]{ new Edge(v1,  7),
	                             new Edge(v2,  4),
                                     new Edge(v3,  1)};

	v1.adjacencies = new Edge[]{ new Edge(v0,  7),
	                             new Edge(v2,  10)};

	v2.adjacencies = new Edge[]{ new Edge(v0,  4),
                                     new Edge(v1,  10),
                                     new Edge(v3,  2)};

	v3.adjacencies = new Edge[]{ new Edge(v0, 1),
                                     new Edge(v2, 2)};


	Vertex[] vertices = { v0, v1, v2, v3 };

System.out.println("***********************************************");
        Dijkstra.computePaths(v2);
        for ( Vertex v : vertices)
	{
	    System.out.println("Distance to " + v + ": " + v.minDistance);
             NewJFrame.jTable2.setValueAt(v.minDistance, i, 2);
	    List<Vertex> path = Dijkstra.getShortestPathTo(v);
	    System.out.println("Path: " + path);
            NewJFrame.jTable2.setValueAt(path, i, 1);
                         i++;



System.out.println("Realiser par Bibomaster");
    }

    }
    if (choix.matches("GW4")) {
 int i =0;
        Vertex v0 = new Vertex("GW1");
	Vertex v1 = new Vertex("GW2");
	Vertex v2 = new Vertex("GW3");
	Vertex v3 = new Vertex("GW4");

	v0.adjacencies = new Edge[]{ new Edge(v1,  7),
	                             new Edge(v2,  4),
                                     new Edge(v3,  1)};

	v1.adjacencies = new Edge[]{ new Edge(v0,  7),
	                             new Edge(v2,  10)};

	v2.adjacencies = new Edge[]{ new Edge(v0,  4),
                                     new Edge(v1,  10),
                                     new Edge(v3,  2)};

	v3.adjacencies = new Edge[]{ new Edge(v0, 1),
                                     new Edge(v2, 2)};


	Vertex[] vertices = { v0, v1, v2, v3 };

System.out.println("***********************************************");
        Dijkstra.computePaths(v3);
        for ( Vertex v : vertices)
	{
	    System.out.println("Distance to " + v + ": " + v.minDistance);
             NewJFrame.jTable2.setValueAt(v.minDistance, i, 2);
             
	    List<Vertex> path = Dijkstra.getShortestPathTo(v);
	    System.out.println("Path: " + path);
            NewJFrame.jTable2.setValueAt(path, i, 1);
                         i++;


System.out.println("Realiser par Bibomaster");
    }

    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable2;
    public static javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
